# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
#  test:
#    docker:
#      - image: circleci/openjdk:8-jdk
#    working_directory: ~/repo
#    environment:
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "build.gradle" }}
#          - v1-dependencies-
#
#      - run: gradle dependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
#      - run: gradle test
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: ls -l
      - persist_to_workspace:
          root: build
          paths:
            - libs
  release:
    docker:
      - image: circleci/golang:1.8

    environment:
      GITHUB_TOKEN: 8bb73578d0b11fad3f8c337519bc108caa145a4b

    steps:
      - attach_workspace:
          at: /build
      - run: ls -l
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=1.0
            ghr -t ${GITHUB_TOKEN} -u ganesanbbc -r PCFLoggerFetcher -c ${CIRCLE_SHA1} -delete ${VERSION} /build/

workflows:
 version: 2

 my_workflow:
  jobs:
#    - test
    - build
#        requires:
#          - test
    - release:
        requires:
          - build


