# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  StaticCodeAnalysis:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'checkout Source'
  Run_UI_Test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Source Analysis '
  Run_Unit_Tests:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Run all Unit Tests'

  SecurityCheck:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Source Analysis '
  BDD:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Source Analysis '

  DevRelease:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Source Analysis '

  IntRelease:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: echo 'Source Analysis '

  Build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: ls -l
      - persist_to_workspace:
          root: build
          paths:
            - libs
  Artifact:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run: ls -l
#      - run:
#          name: "Publish Release on GitHub"
#          command: |
#            go get github.com/tcnksm/ghr
#            VERSION=1.1
#            ghr -t 6c1865243acaaa3565770f29948de64ac3182b1f -u ganesanbbc -r PCFLoggerFetcher ${VERSION} /

workflows:
 version: 2

 my_workflow:
  jobs:
    - StaticCodeAnalysis
    - Run_UI_Test
    - Run_Unit_Tests
    - SecurityCheck:
        requires:
          - Run_Unit_Tests
          - StaticCodeAnalysis
          - Run_UI_Test
    - Build:
        requires:
          - SecurityCheck
    - DevRelease:
        requires:
          - SecurityCheck
    - BDD:
        requires:
          - DevRelease
          - Build
    - Artifact:
        requires:
          - BDD
    - IntRelease:
        requires:
          - Artifact


